{% set name = "ophyd" %}
{% set version = "1.3.3" %}
{% set sha256 = "1526e5e934b4c85a9d51f822e69ac45913f308043221abd0316b922350034cbf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: ophyd-v{{ version }}.tar.gz
  url: https://github.com/NSLS-II/ophyd/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches: 
    - windows.patch
    - ophyd.patch

build:
  number: 3
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [py2k]

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - networkx
    - numpy

test:
  imports:
    - ophyd
    - ophyd.utils
    - ophyd.areadetector
    - ophyd.sim

about:
  home: https://github.com/NSLS-II/ophyd
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Ophyd - EPICS Client Abstractions'

extra:
  recipe-maintainers:
    - CJ-Wright
    - conda-forge/event-model
