{% set name = "ophyd" %}
{% set version = "1.3.0" %}
{% set sha256 = "1d957a27f4725763fadfe10bdc42cd3d1865e719d6d34489bde7363a6011bb62" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: ophyd-v{{ version }}.tar.gz
  url: https://github.com/NSLS-II/ophyd/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [py2k or win]

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - networkx
    - numpy

test:
  imports:
    - ophyd
    - ophyd.utils
    - ophyd.areadetector
    - ophyd.sim

about:
  home: https://github.com/NSLS-II/ophyd
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Ophyd - EPICS Client Abstractions'

extra:
  recipe-maintainers:
    - CJ-Wright
