# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_python3.6
    - CONFIG=osx_python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "XW2pHh6gq8cfoIR2vQ68ZcA47Z+J0jWS+fbF2ybhRmM1BwgI7LsYpMtCF5WesFbcNqKHGB1UE/iWCWRvyj4Jw8ssKDbL2zJDq1edEsBBhCfJOv21i1+LqbVNwvm3/QDLr+rsp3th+hzjgsZQhl5WDSlaF/PfkPHxmXiiUwACycWyd1akJWcvlzg539ViQMQ4fXMw1YGDcvgLIf8c7At+2GioTfNE1ah2w7rsM6NSVQwevb6ZKZlpI26EjCFvV2m6uS4+VjZYznmxnPM8Va3zRpVIxZn3Ze+pWaiq7rFSZ0iE5QXvBmw74EjW8PDfiK+SwyUQD8y346e+dtYO00nu2o37lnYeX1cvty7B9IKuwmq2IOJk7DWmx+29q/iHzvunsTT1d9yRh1ITnSnRbwCcb8TueO2ZVxFdqD2w6y5jNx1KQyinOnYAOLFN+BWDC97LBtnio8T+gdLLYcLtiUBGg64SxV+hk/IYkA8rA8UAqh219uoq71gDAALB/Bp1rbE8F3yU5IwnzyQJL6s9Ur9MYGZgc005mxqKs6Sf1kmrFSNv+dwXbyDjzU/ibwMGmdu2XU+YJAX6mQgrcK/mfUHLNw+JJE78hjJaLTfEciugtTUZbMXOIyQyvnU1j/kN+kMoDVfsrz4j4QyKgYqwF6uFdor/22pvmeaNNrjHem7icec="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml