travis:
  secure:
    BINSTAR_TOKEN: q2s0cxqhj0sauQfqW0PUJsltEcKUeT5A1Hcn+10STIevpNdqFjWWNQehOLt10g4pjbKFe6s0ri7Jpk6W3wWiiXIR28lZ2nUn0dixYl/xKsFkgacV77En+TPvoZDkylvu9q9c9DS9Uyqs33zyeW1r0HMZbHsQM7eSdaUCug9wt88awyvpSSYdmYHk60APdau4sgTcjDIH50+vL+X4XvpRY43p5u4TjpMoJA1hBDU7Yh2VA5E713/2J9V19lQsTzxvtd+rl+RpbFZt8S1zmXtWYpqdo3pNWCKc9YAf7hKs9eALJF5KYolwNAPV5TlsbnzH22jMuoRU6EpAi4NOHBrymWipV/1Q5X3dX4U5lR4suo2KgWoLSemlDnWbGvmfuq5CKKXz8W7wvek9fj5EDhoQ04u9vHvBYZTpbAneUMkhtpukzm5eWJCKrQpMZ89lkDDY0RO0kEWvHQa649l4PyWG8ioWFpSqajR1oWcsLkfnDtZZWxUGJ8gzDuAt8zjG6YDxP57cJyiUdrN1MuamJbfdpSM3IXa8VtTWA9GFmbTmtJ/9Tj4mmPGUpp4kBdv99IXe+uzbzsLccbt1uA/lhHESDQ2v6KKTSGC3SoW/L3I9Wz5HrbI37X1hDQg1eF09D9iMHaecauN9lgAEw90ZRpvEU4OdQlK4NpKHjCHku+SeHeI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
